/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IRandomNumberProvider,
  IRandomNumberProviderInterface,
} from "../IRandomNumberProvider";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "requestId",
        type: "bytes32",
      },
    ],
    name: "getRandomRequestResult",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "requestRandomNumber",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IRandomNumberProvider__factory {
  static readonly abi = _abi;
  static createInterface(): IRandomNumberProviderInterface {
    return new utils.Interface(_abi) as IRandomNumberProviderInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IRandomNumberProvider {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IRandomNumberProvider;
  }
}
