/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface RewardConfigurationProviderMockInterface
  extends ethers.utils.Interface {
  functions: {
    "getMaxReward(uint256,uint256,uint256)": FunctionFragment;
    "getUnlockedReward(uint256,uint256,uint256,uint256,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getMaxReward",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUnlockedReward",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "getMaxReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUnlockedReward",
    data: BytesLike
  ): Result;

  events: {};
}

export class RewardConfigurationProviderMock extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: RewardConfigurationProviderMockInterface;

  functions: {
    getMaxReward(
      initialTokenSupply: BigNumberish,
      weight: BigNumberish,
      totalWeight: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getUnlockedReward(
      mintTimestamp: BigNumberish,
      timestamp: BigNumberish,
      initialTokenSupply: BigNumberish,
      weight: BigNumberish,
      totalWeight: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;
  };

  getMaxReward(
    initialTokenSupply: BigNumberish,
    weight: BigNumberish,
    totalWeight: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getUnlockedReward(
    mintTimestamp: BigNumberish,
    timestamp: BigNumberish,
    initialTokenSupply: BigNumberish,
    weight: BigNumberish,
    totalWeight: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    getMaxReward(
      initialTokenSupply: BigNumberish,
      weight: BigNumberish,
      totalWeight: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getUnlockedReward(
      mintTimestamp: BigNumberish,
      timestamp: BigNumberish,
      initialTokenSupply: BigNumberish,
      weight: BigNumberish,
      totalWeight: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    getMaxReward(
      initialTokenSupply: BigNumberish,
      weight: BigNumberish,
      totalWeight: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getUnlockedReward(
      mintTimestamp: BigNumberish,
      timestamp: BigNumberish,
      initialTokenSupply: BigNumberish,
      weight: BigNumberish,
      totalWeight: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getMaxReward(
      initialTokenSupply: BigNumberish,
      weight: BigNumberish,
      totalWeight: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getUnlockedReward(
      mintTimestamp: BigNumberish,
      timestamp: BigNumberish,
      initialTokenSupply: BigNumberish,
      weight: BigNumberish,
      totalWeight: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
