/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface StrategyManagerInterface extends ethers.utils.Interface {
  functions: {
    "DEFAULT_FRAGMENT()": FunctionFragment;
    "DEFAULT_FRAGMENT_HASH()": FunctionFragment;
    "addFragment(string)": FunctionFragment;
    "addFragments(string[])": FunctionFragment;
    "fragmentExists(string)": FunctionFragment;
    "fragmentPointers(bytes32)": FunctionFragment;
    "fragments(uint256)": FunctionFragment;
    "owner()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "DEFAULT_FRAGMENT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_FRAGMENT_HASH",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "addFragment", values: [string]): string;
  encodeFunctionData(
    functionFragment: "addFragments",
    values: [string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "fragmentExists",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "fragmentPointers",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "fragments",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_FRAGMENT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_FRAGMENT_HASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addFragment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addFragments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fragmentExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fragmentPointers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fragments", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;

  events: {
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export type OwnershipTransferredEvent = TypedEvent<
  [string, string] & { previousOwner: string; newOwner: string }
>;

export class StrategyManager extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: StrategyManagerInterface;

  functions: {
    DEFAULT_FRAGMENT(overrides?: CallOverrides): Promise<[string]>;

    DEFAULT_FRAGMENT_HASH(overrides?: CallOverrides): Promise<[string]>;

    addFragment(
      _fragment: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    addFragments(
      _fragments: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    fragmentExists(
      _fragment: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    fragmentPointers(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    fragments(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string] & { selector: string }>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  DEFAULT_FRAGMENT(overrides?: CallOverrides): Promise<string>;

  DEFAULT_FRAGMENT_HASH(overrides?: CallOverrides): Promise<string>;

  addFragment(
    _fragment: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  addFragments(
    _fragments: string[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  fragmentExists(
    _fragment: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  fragmentPointers(
    arg0: BytesLike,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  fragments(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  owner(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    DEFAULT_FRAGMENT(overrides?: CallOverrides): Promise<string>;

    DEFAULT_FRAGMENT_HASH(overrides?: CallOverrides): Promise<string>;

    addFragment(_fragment: string, overrides?: CallOverrides): Promise<void>;

    addFragments(
      _fragments: string[],
      overrides?: CallOverrides
    ): Promise<void>;

    fragmentExists(
      _fragment: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    fragmentPointers(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    fragments(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;
  };

  estimateGas: {
    DEFAULT_FRAGMENT(overrides?: CallOverrides): Promise<BigNumber>;

    DEFAULT_FRAGMENT_HASH(overrides?: CallOverrides): Promise<BigNumber>;

    addFragment(
      _fragment: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    addFragments(
      _fragments: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    fragmentExists(
      _fragment: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    fragmentPointers(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    fragments(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    DEFAULT_FRAGMENT(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    DEFAULT_FRAGMENT_HASH(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    addFragment(
      _fragment: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    addFragments(
      _fragments: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    fragmentExists(
      _fragment: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    fragmentPointers(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    fragments(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
