name: Deploy Preview
on:
  pull_request:
    branches:
      - master
jobs:
  app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_APP_PROJECT_ID}}
          alias-domains: |
            {{BRANCH}}-{{PR_NUMBER}}-preview-demoslabs.vercel.app
